### ISSUE TITLE
Error while running simulation (bad operand type, self.entry_fee)

### ISSUE THREAD

**Issue by jturbzz** [chanzer0/nfl_optimizer#15]
First, big thanks for creating this!

I can't seem to successfully run the sim, for either FD or DK. The error I get is the following:

![image](https://user-images.githubusercontent.com/30187005/216128828-5f1fad84-d8a1-48cb-b320-0fd0a1faae7a.png)

Any thoughts on what I might be doing wrong would be appreciated.

Thanks!

**Comment by chanzer0** [comment]
We just pushed some changes, I'd recommend pulling the latest code down and running again to see if you encounter the same issue.
