### ISSUE TITLE
Not an issue just a dummy

### ISSUE THREAD

**Issue by DFSDFSDFS11** [chanzer0/nfl_optimizer#18]
Hey Chanzer, I love the idea of your tools and I am a huge DFS fan whos been looking for a tool like this, specifically the excel sheet that shows optimal, top 10% win% etc, However I keep getting an error when I am trying to run optimal lineups to receive outputs that show those stats. The following message keeps occurring : PS C:\Users\colin\OneDrive\Desktop\NBA-DFS-Tools-master\src> python .\main.py dk opto 1000 0 rand
Traceback (most recent call last):
  File "C:\Users\colin\OneDrive\Desktop\NBA-DFS-Tools-master\src\main.py", line 63, in <module>
    main(sys.argv)
  File "C:\Users\colin\OneDrive\Desktop\NBA-DFS-Tools-master\src\main.py", line 21, in main
    opto = NBA_Optimizer(site, num_lineups, num_uniques)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\colin\OneDrive\Desktop\NBA-DFS-Tools-master\src\nba_optimizer.py", line 36, in __init__
    self.load_config()
  File "C:\Users\colin\OneDrive\Desktop\NBA-DFS-Tools-master\src\nba_optimizer.py", line 60, in load_config
    with open(os.path.join(os.path.dirname(__file__), '../config.json'), encoding='utf-8-sig') as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\colin\\OneDrive\\Desktop\\NBA-DFS-Tools-master\\src\\../config.json'
PS C:\Users\colin\OneDrive\Desktop\NBA-DFS-Tools-master\src>

Is there an issue with my JSON file? And would there be a code I could input that would allow for me to input my lineups, and receive the output in the excel sheet? Sorry if all of these questions are ridiculous but thank you so much for all you do!

**Comment by chanzer0** [comment]
Marking as resolved, we are addressing this via email.

For those in the future looking: Please be sure you have file extensions enbaled on Windows. The common issue here is people do not have file extensions on, so when they go to rename the file to `config.json`, they're actually naming it `config.json.json` unkowingly.

![image](https://user-images.githubusercontent.com/25206712/220696693-997f2ac3-26b8-464a-8313-05171034c796.png)

**Comment by terrellbradford** [comment]
Similar as DFSDFSDFS11. I conformed config.json not config.json.json

PS U:\NBA-DFS-Tools\src> python .\main.py dk opto 100 2
Traceback (most recent call last):
  File ".\main.py", line 63, in <module>
    main(sys.argv)
  File ".\main.py", line 21, in main
    opto = NBA_Optimizer(site, num_lineups, num_uniques)
  File "U:\NBA-DFS-Tools\src\nba_optimizer.py", line 37, in __init__
    self.load_rules()
  File "U:\NBA-DFS-Tools\src\nba_optimizer.py", line 94, in load_rules
    self.matchup_limits = self.config["matchup_limits"]
KeyError: 'matchup_limits'

**Comment by chanzer0** [comment]
@terrellbradford  This error is indicating that you are missing "matchup_limits" key from your `config.json` file.

To fix, just add this key to your config file:
```
"matchup_limits": {},
```

and to use it if you want:
```
"matchup_limits": {
     "SAC@IND": 3,
},
```
This rule would result in at most 3 players being included from the Kings Pacers game
