### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by doublec1985** [chanzer0/nfl_optimizer#19]
Have you thought about expanding to all sports, and creating a GUI.

Also, I think it would be cool to have a db of FanDuel contest history. To see what top players are doing day to day. I know fantasy cruncher has rewind for DK, but nothing for FD since they done make csv’s of contests available. So you will need to scrape contest data from FD. I think this could be huge. If you want help let me know I started attempting this but it def needs upgrades.

**Comment by chanzer0** [comment]
Hey @doublec1985 - We currently do support more sports if you check my other repositories. We have also recently released https://acemind.io, which is our website built on top of tools here. I encourage you to check those out or come say hi in our discord where there's tons of other folks using the tools and helping one another - https://discord.gg/SkRJKyZJ7y

**Comment by doublec1985** [comment]
What about FanDuel Tournament history?

**Comment by chanzer0** [comment]
We've got a few other things with higher priorities at the moment, but providing some sort of contest history tool I think would be cool to have!

**Comment by doublec1985** [comment]
It would set you apart from everyone because no one has it.

Sent from my iPhone

On Nov 2, 2023, at 10:34 AM, Sean ***@***.***> wrote:

﻿

We've got a few other things with higher priorities at the moment, but providing some sort of contest history tool I think would be cool to have!
