### ISSUE TITLE
"GameTime" KeyError with new Swaptimizer code

### ISSUE THREAD

**Issue by eddiesteinfeld** [chanzer0/nfl_optimizer#29]
Are there any other changes that need to be made for the updated Swaptimizer to function properly?

Getting the following error when running it and have not changed any other files aside from the Swaptimizer and Opto from latest branch

![gametime keyerror](https://github.com/chanzer0/NBA-DFS-Tools/assets/161541604/05ffd8c1-9e70-4610-87ff-0ca5574977cf)

**Comment by chanzer0** [comment]
I will do some testing and get back to you @eddiesteinfeld. I'd also recommend joining our discord to discuss errors and whatnot, we're typically more responsive there (although I still do appreciate you creating a ticket here) -- https://discord.gg/bqPFDDPCB7

**Comment by chanzer0** [comment]
I believe I have fixed this in my most recent updates. If you still encounter the issue, please open up another ticket.
