### ISSUE TITLE
Hyphenated Name in FD

### ISSUE THREAD

**Issue by jgabbydfs** [chanzer0/nfl_optimizer#3]
Love your simulator but it seems like you have a bug with hyphenated players in FD (Luwawu-Cabarrot and Anthony-Towns tonight for example). It optimizes with them but includes them as zeroes across the board except for 0.1% for ownership.

**Comment by rickenrocker24** [comment]
> Love your simulator but it seems like you have a bug with hyphenated players in FD (Luwawu-Cabarrot and Anthony-Towns tonight for example). It optimizes with them but includes them as zeroes across the board except for 0.1% for ownership.

Hello jgabbydfs,
Have you tried running "python .\name_change.py" first? this should update the names. 

Ric

**Comment by chanzer0** [comment]
Yes, if you have issues with IDs not loading properly, be sure to run `python .\name_change.py` first

**Comment by jgabbydfs** [comment]
I ran the name change first but it was still incorrect with the hyphens. I’m running sims so not sure if the issue has to do with replacing hyphens in contest data (I’m not using contest data but could be the cause) causing hyphens to be replaced in the players names. They actually have their FD ID pull in but it doesn’t pull in any of their projections from the list. I create my own projections but formatted them to Alex’s templates to meet the criteria.

**Comment by jgabbydfs** [comment]
I should clarify the names being pulled in with the IDs do have the hyphens. Not sure if there’s an issue in my list but everything seems to match. I use a small player pool and the only two names that didn’t work were Luwawu-Cabarrott and Karl-Anthony

**Comment by chanzer0** [comment]
Can you send me an email at seansailer28@gmail with the input files you are using and the command you are running? I can look into this for you

**Comment by jgabbydfs** [comment]
New update fixed this issue. Thanks!
