### ISSUE TITLE
Tourney Lineup Issue

### ISSUE THREAD

**Issue by aggiefury101** [chanzer0/nfl_optimizer#6]
Hi,

I'm a FD player and had some questions about the gpp sim process.

1.  I should run the opto first to generate a set # of lineups then run those against the contest im in to see optimal outcomes correct?
2. I cant seem to gather the contest structure for FD is it the same csv structure for DK? Any way to automate that process?
3. What is the process for running a large ggp tourney? For example the field size for a 0.05 contest is over 200,000 with a max of 150 entries. does having premade lineups speed up the process of calculating those numbers?

I appreciate your time in responding! Awesome tool.

**Comment by chanzer0** [comment]
1. Yes, if you're using the GPP simulator tool, I would recommend generating lineups via the opto command (probably with randomness enabled) to generate a list of lineups
2. Automating for FD a bit tougher, you'll likely have to take a few minutes to manually create the structure -- you want it to look just as the example provided
3. Premade lineups definitely speeds up the GPP simulator process, however for a contest of size >10,000, I would recommend creating a smaller scale version of the tournament, as generating that many lineups is going to take too long

For example - a 200k person contest with 0.05 entry cost, I would generate perhaps 10,000 lineups (1/20th the size) and then divide the entry cost and the payout structure by that number as well to create an accurate representation of the "smaller scale" tournament



=== *UPDATE* ===
I am working with a partner of mine to drastically speed up and fine-tune the simulation process so hopefully in the future the large contest sizes will still be viable to generate on-the-fly
