### ISSUE TITLE
Not Creating Set amount of Lineups.

### ISSUE THREAD

**Issue by BeeRabbits** [chanzer0/nfl_optimizer#9]
Sorry, another issue i am having is i set the Opto lineups to 500 and it creates about 12-40 each time 
![image](https://user-images.githubusercontent.com/120123974/206520999-caac4e88-e4ab-4228-8f7d-14f23a8d0d4f.png)

![image](https://user-images.githubusercontent.com/120123974/206521048-c852683c-fb34-4e39-9a53-eb5fefdb7974.png)

I followed your video and instructions i thought very well. Not sure exactly what's going on.

**Comment by chanzer0** [comment]
Can you contact me on discord via friend request/direct message? I'd be happy to help you find out what's going on

Discord: `chanzero#1862`

**Comment by BeeRabbits** [comment]
You aren't accepting Friends Requests at this time lol, My discord is `Chealol#5216`

**Comment by chanzer0** [comment]
Closing this issue, we resolved via discord.
